#!/bin/bash

echo "🔍 Deploying DEBUG version to diagnose Unknown Product issue"
echo "======================================================"
echo ""
echo "📋 DEPLOYMENT COMMANDS (run on EC2):"
echo ""
echo "# 1. Pull latest debug code"
echo "git pull origin main"
echo ""
echo "# 2. Rebuild frontend with debug logging (NO CACHE!)"
echo "docker-compose -f docker-compose.prod.yml down"
echo "docker-compose -f docker-compose.prod.yml build --no-cache frontend"
echo "docker-compose -f docker-compose.prod.yml up -d"
echo ""
echo "# 3. Verify deployment"
echo "docker-compose -f docker-compose.prod.yml logs -f frontend | head -20"
echo ""
echo "🔍 DEBUG ANALYSIS STEPS:"
echo "======================================================"
echo ""
echo "1. Open: https://ursaviour.com/products.html"
echo ""
echo "2. Open Browser Developer Tools (F12)"
echo "   - Go to Console tab"
echo "   - Look for these debug messages:"
echo ""
echo "   ✅ Expected success messages:"
echo "   - '[Products] Raw API data received:' (shows full API response)"
echo "   - '[Products] Extracted products array:' (shows extracted products)"
echo "   - '[Normalize] Processing store X:' (shows each store's raw data)"
echo "   - '[Normalize] Store mapping:' (shows field mapping)"
echo "   - '[Normalize] Product X FINAL:' (shows normalized result)"
echo ""
echo "   🚨 Look for error patterns:"
echo "   - 'Unknown Product' in normalized results"
echo "   - stores_count: 0 (indicates store processing failure)"
echo "   - Missing store_name or final_price fields"
echo ""
echo "3. COPY CONSOLE OUTPUT and share for analysis"
echo ""
echo "🎯 EXPECTED FIXES AFTER ANALYSIS:"
echo "======================================================"
echo "- Products should show: 'Mineral Water', 'Lettuce', etc."
echo "- Prices should show: \$11.94, \$4.99, etc. (not \$0.00)"
echo "- Categories: 'Beverages', 'Fruit', etc. (not 'Uncategorized')"
echo "- 100 products with 4 stores each = 400 store entries total"
echo ""
echo "Cache busting: v=2025101807"