services:
  api:
    build: ./backend
    env_file: ./backend/.env
    ports: ["8000:8000"]
    depends_on: [db, mailhog]
    volumes: ["./backend:/app"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ursaviour
      MYSQL_USER: ursaviour
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports: ["3306:3306"]
    volumes: [dbdata:/var/lib/mysql]

  adminer:
    image: adminer
    restart: unless-stopped
    ports: ["8080:8080"]

  mailhog:
    image: mailhog/mailhog
    ports: ["8025:8025"]  # Web UI; SMTP: 1025 internal

volumes:
  dbdata:
