version: '3.9'

services:
  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      # ── RDS connection basic information ──────────────────────────────────────────────
      - DB_HOST=ursaviour-db.cp4emoqegwfy.ap-southeast-2.rds.amazonaws.com
      - DB_PORT=3306
      - DB_NAME=ursaviour
      - DB_USER=admin
      - DB_PASSWORD=Ursaviour2025
      #for SQLAlchemy
      - DATABASE_URL=mysql+pymysql://admin:Ursaviour2025@ursaviour-db.cp4emoqegwfy.ap-southeast-2.rds.amazonaws.com:3306/ursaviour
